version: "3.1"
services:
  db:
    env_file:
      - .env
    image: "postgres:${POSTGRES_VERSION}"
    privileged: true
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}

  backend:
    build:
      context: ./todo_prj/
    expose:
      - 8000
    command: bash -c "
      python manage.py migrate
      && python manage.py users_create
      && python manage.py projects_todos_create
      && gunicorn todo_prj.wsgi -b 127.0.0.1:8000
      "
    depends_on:
      - db

  nginx:
    build: ./todo_prj/nginx/
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./todo_prj/frontend/
    ports:
      - 80:80
    depends_on:
      - nginx
