version: "3.8"
services:
  db:
    env_file:
      - .env
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - pg-data:/var/lib/postgresql/data/
    privileged: true
    ports:
      - 5432:5432
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/todo_prj/
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    build: .
    expose:
      - 8080
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py users_create
      && python manage.py projects_todos_create
      && gunicorn todo_prj.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx

volumes:
  pg-data:
